name: dart_server
description: Nervatura Examples Dart server.
version: 1.0.0

publish_to: "none"

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  services:
    path: ../services
  dotenv: ^4.1.0
  shelf_cors_headers: ^0.1.4
  http: ^0.13.0
  dart_jsonwebtoken: ^2.7.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0