<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *RequestUpdate Key->ID keys:
 *- ```id```: The value is a generated constant key identifier: *{nervatype}/{refnumber}~{rownumber}*. The rownumber is the order of multiple *{nervatype}/{refnumber}* keys.
 *- ```nervatype```: Valid values: *customer, employee, event, place, product, project, tool, trans*
 *- ```ref_id```: Valid values: *customer/{custnumber}, employee/{empnumber}, event/{calnumber}, place/{planumber}, product/{partnumber}, project/{pronumber}, tool/{serial}, trans/{transnumber}*
 *
 * Generated from protobuf message <code>nervatura.Contact</code>
 */
class Contact extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Reference to [Groups](#groups).id (only where groupname = 'nervatype')
     *
     * Generated from protobuf field <code>int64 nervatype = 2;</code>
     */
    protected $nervatype = 0;
    /**
     * Reference to [Customer](#customer).id, [Employee](#employee).id, [Event](#event).id, [Place](#place).id, [Product](#product).id, [Project](#project).id, [Tool](#tool).id, [Trans](#trans).id
     *
     * Generated from protobuf field <code>int64 ref_id = 3;</code>
     */
    protected $ref_id = 0;
    /**
     * Generated from protobuf field <code>string firstname = 4;</code>
     */
    protected $firstname = '';
    /**
     * Generated from protobuf field <code>string surname = 5;</code>
     */
    protected $surname = '';
    /**
     * Generated from protobuf field <code>string status = 6;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string phone = 7;</code>
     */
    protected $phone = '';
    /**
     * Generated from protobuf field <code>string fax = 8;</code>
     */
    protected $fax = '';
    /**
     * Generated from protobuf field <code>string mobil = 9;</code>
     */
    protected $mobil = '';
    /**
     * Generated from protobuf field <code>string email = 10;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string notes = 11;</code>
     */
    protected $notes = '';
    /**
     * Contact meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 12;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $nervatype
     *           Reference to [Groups](#groups).id (only where groupname = 'nervatype')
     *     @type int|string $ref_id
     *           Reference to [Customer](#customer).id, [Employee](#employee).id, [Event](#event).id, [Place](#place).id, [Product](#product).id, [Project](#project).id, [Tool](#tool).id, [Trans](#trans).id
     *     @type string $firstname
     *     @type string $surname
     *     @type string $status
     *     @type string $phone
     *     @type string $fax
     *     @type string $mobil
     *     @type string $email
     *     @type string $notes
     *     @type \Nervatura\MetaData[]|\Google\Protobuf\Internal\RepeatedField $metadata
     *           Contact meta data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'nervatype')
     *
     * Generated from protobuf field <code>int64 nervatype = 2;</code>
     * @return int|string
     */
    public function getNervatype()
    {
        return $this->nervatype;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'nervatype')
     *
     * Generated from protobuf field <code>int64 nervatype = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNervatype($var)
    {
        GPBUtil::checkInt64($var);
        $this->nervatype = $var;

        return $this;
    }

    /**
     * Reference to [Customer](#customer).id, [Employee](#employee).id, [Event](#event).id, [Place](#place).id, [Product](#product).id, [Project](#project).id, [Tool](#tool).id, [Trans](#trans).id
     *
     * Generated from protobuf field <code>int64 ref_id = 3;</code>
     * @return int|string
     */
    public function getRefId()
    {
        return $this->ref_id;
    }

    /**
     * Reference to [Customer](#customer).id, [Employee](#employee).id, [Event](#event).id, [Place](#place).id, [Product](#product).id, [Project](#project).id, [Tool](#tool).id, [Trans](#trans).id
     *
     * Generated from protobuf field <code>int64 ref_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRefId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ref_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string firstname = 4;</code>
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Generated from protobuf field <code>string firstname = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstname($var)
    {
        GPBUtil::checkString($var, True);
        $this->firstname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string surname = 5;</code>
     * @return string
     */
    public function getSurname()
    {
        return $this->surname;
    }

    /**
     * Generated from protobuf field <code>string surname = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSurname($var)
    {
        GPBUtil::checkString($var, True);
        $this->surname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 6;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 7;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fax = 8;</code>
     * @return string
     */
    public function getFax()
    {
        return $this->fax;
    }

    /**
     * Generated from protobuf field <code>string fax = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setFax($var)
    {
        GPBUtil::checkString($var, True);
        $this->fax = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mobil = 9;</code>
     * @return string
     */
    public function getMobil()
    {
        return $this->mobil;
    }

    /**
     * Generated from protobuf field <code>string mobil = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setMobil($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobil = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 10;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string notes = 11;</code>
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Generated from protobuf field <code>string notes = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->notes = $var;

        return $this;
    }

    /**
     * Contact meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Contact meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 12;</code>
     * @param \Nervatura\MetaData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\MetaData::class);
        $this->metadata = $arr;

        return $this;
    }

}

