<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.DataType</code>
 */
class DataType
{
    /**
     * Address
     *
     * Generated from protobuf enum <code>address = 0;</code>
     */
    const address = 0;
    /**
     * Barcode
     *
     * Generated from protobuf enum <code>barcode = 1;</code>
     */
    const barcode = 1;
    /**
     * Contact
     *
     * Generated from protobuf enum <code>contact = 2;</code>
     */
    const contact = 2;
    /**
     * Currency
     *
     * Generated from protobuf enum <code>currency = 3;</code>
     */
    const currency = 3;
    /**
     * Customer
     *
     * Generated from protobuf enum <code>customer = 4;</code>
     */
    const customer = 4;
    /**
     * Deffield
     *
     * Generated from protobuf enum <code>deffield = 5;</code>
     */
    const deffield = 5;
    /**
     * Employee
     *
     * Generated from protobuf enum <code>employee = 6;</code>
     */
    const employee = 6;
    /**
     * Event
     *
     * Generated from protobuf enum <code>event = 7;</code>
     */
    const event = 7;
    /**
     * Fieldvalue
     *
     * Generated from protobuf enum <code>fieldvalue = 8;</code>
     */
    const fieldvalue = 8;
    /**
     * Groups
     *
     * Generated from protobuf enum <code>groups = 9;</code>
     */
    const groups = 9;
    /**
     * Item
     *
     * Generated from protobuf enum <code>item = 10;</code>
     */
    const item = 10;
    /**
     * Link
     *
     * Generated from protobuf enum <code>link = 11;</code>
     */
    const link = 11;
    /**
     * Log
     *
     * Generated from protobuf enum <code>log = 12;</code>
     */
    const log = 12;
    /**
     * Movement
     *
     * Generated from protobuf enum <code>movement = 13;</code>
     */
    const movement = 13;
    /**
     * Numberdef
     *
     * Generated from protobuf enum <code>numberdef = 14;</code>
     */
    const numberdef = 14;
    /**
     * Pattern
     *
     * Generated from protobuf enum <code>pattern = 15;</code>
     */
    const pattern = 15;
    /**
     * Payment
     *
     * Generated from protobuf enum <code>payment = 16;</code>
     */
    const payment = 16;
    /**
     * Place
     *
     * Generated from protobuf enum <code>place = 17;</code>
     */
    const place = 17;
    /**
     * Price
     *
     * Generated from protobuf enum <code>price = 18;</code>
     */
    const price = 18;
    /**
     * Product
     *
     * Generated from protobuf enum <code>product = 19;</code>
     */
    const product = 19;
    /**
     * Project
     *
     * Generated from protobuf enum <code>project = 20;</code>
     */
    const project = 20;
    /**
     * Rate
     *
     * Generated from protobuf enum <code>rate = 21;</code>
     */
    const rate = 21;
    /**
     * Tax
     *
     * Generated from protobuf enum <code>tax = 22;</code>
     */
    const tax = 22;
    /**
     * Tool
     *
     * Generated from protobuf enum <code>tool = 23;</code>
     */
    const tool = 23;
    /**
     * Trans
     *
     * Generated from protobuf enum <code>trans = 24;</code>
     */
    const trans = 24;
    /**
     * UiAudit
     *
     * Generated from protobuf enum <code>ui_audit = 25;</code>
     */
    const ui_audit = 25;
    /**
     * UiMenu
     *
     * Generated from protobuf enum <code>ui_menu = 26;</code>
     */
    const ui_menu = 26;
    /**
     * UiMenufields
     *
     * Generated from protobuf enum <code>ui_menufields = 27;</code>
     */
    const ui_menufields = 27;
    /**
     * UiMessage
     *
     * Generated from protobuf enum <code>ui_message = 28;</code>
     */
    const ui_message = 28;
    /**
     * UiPrintqueue
     *
     * Generated from protobuf enum <code>ui_printqueue = 29;</code>
     */
    const ui_printqueue = 29;
    /**
     * UiReport
     *
     * Generated from protobuf enum <code>ui_report = 30;</code>
     */
    const ui_report = 30;
    /**
     * UiUserconfig
     *
     * Generated from protobuf enum <code>ui_userconfig = 31;</code>
     */
    const ui_userconfig = 31;

    private static $valueToName = [
        self::address => 'address',
        self::barcode => 'barcode',
        self::contact => 'contact',
        self::currency => 'currency',
        self::customer => 'customer',
        self::deffield => 'deffield',
        self::employee => 'employee',
        self::event => 'event',
        self::fieldvalue => 'fieldvalue',
        self::groups => 'groups',
        self::item => 'item',
        self::link => 'link',
        self::log => 'log',
        self::movement => 'movement',
        self::numberdef => 'numberdef',
        self::pattern => 'pattern',
        self::payment => 'payment',
        self::place => 'place',
        self::price => 'price',
        self::product => 'product',
        self::project => 'project',
        self::rate => 'rate',
        self::tax => 'tax',
        self::tool => 'tool',
        self::trans => 'trans',
        self::ui_audit => 'ui_audit',
        self::ui_menu => 'ui_menu',
        self::ui_menufields => 'ui_menufields',
        self::ui_message => 'ui_message',
        self::ui_printqueue => 'ui_printqueue',
        self::ui_report => 'ui_report',
        self::ui_userconfig => 'ui_userconfig',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtolower($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

