<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *RequestUpdate Key->ID keys:
 *- ```id```: The value is a generated constant key identifier: *{refnumber}~~{fieldname}~{rownumber}*. The rownumber is the order of multiple *{refnumber}~~{fieldname}* keys.
 *- ```ref_id```: Valid values: *{nervatype}/{refnumber}*
 *
 * Generated from protobuf message <code>nervatura.Fieldvalue</code>
 */
class Fieldvalue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Reference to [Deffield](#deffield).fieldname.
     *
     * Generated from protobuf field <code>string fieldname = 2;</code>
     */
    protected $fieldname = '';
    /**
     * Reference to any type.id where type = [Deffield](#deffield).nervatype. If it is null then nervatype = setting.
     *
     * Generated from protobuf field <code>int64 ref_id = 3;</code>
     */
    protected $ref_id = null;
    /**
     * Generated from protobuf field <code>string value = 4;</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>string notes = 5;</code>
     */
    protected $notes = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $fieldname
     *           Reference to [Deffield](#deffield).fieldname.
     *     @type int|string $ref_id
     *           Reference to any type.id where type = [Deffield](#deffield).nervatype. If it is null then nervatype = setting.
     *     @type string $value
     *     @type string $notes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Reference to [Deffield](#deffield).fieldname.
     *
     * Generated from protobuf field <code>string fieldname = 2;</code>
     * @return string
     */
    public function getFieldname()
    {
        return $this->fieldname;
    }

    /**
     * Reference to [Deffield](#deffield).fieldname.
     *
     * Generated from protobuf field <code>string fieldname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fieldname = $var;

        return $this;
    }

    /**
     * Reference to any type.id where type = [Deffield](#deffield).nervatype. If it is null then nervatype = setting.
     *
     * Generated from protobuf field <code>int64 ref_id = 3;</code>
     * @return int|string
     */
    public function getRefId()
    {
        return isset($this->ref_id) ? $this->ref_id : 0;
    }

    public function hasRefId()
    {
        return isset($this->ref_id);
    }

    public function clearRefId()
    {
        unset($this->ref_id);
    }

    /**
     * Reference to any type.id where type = [Deffield](#deffield).nervatype. If it is null then nervatype = setting.
     *
     * Generated from protobuf field <code>int64 ref_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRefId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ref_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 4;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string notes = 5;</code>
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Generated from protobuf field <code>string notes = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->notes = $var;

        return $this;
    }

}

