<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *RequestUpdate Key->ID keys:
 *- ```id```: Group *groupname~groupvalue*
 *
 * Generated from protobuf message <code>nervatura.Groups</code>
 */
class Groups extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string groupname = 2;</code>
     */
    protected $groupname = '';
    /**
     * Generated from protobuf field <code>string groupvalue = 3;</code>
     */
    protected $groupvalue = '';
    /**
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>bool inactive = 5;</code>
     */
    protected $inactive = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $groupname
     *     @type string $groupvalue
     *     @type string $description
     *     @type bool $inactive
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string groupname = 2;</code>
     * @return string
     */
    public function getGroupname()
    {
        return $this->groupname;
    }

    /**
     * Generated from protobuf field <code>string groupname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupname($var)
    {
        GPBUtil::checkString($var, True);
        $this->groupname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string groupvalue = 3;</code>
     * @return string
     */
    public function getGroupvalue()
    {
        return $this->groupvalue;
    }

    /**
     * Generated from protobuf field <code>string groupvalue = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupvalue($var)
    {
        GPBUtil::checkString($var, True);
        $this->groupvalue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool inactive = 5;</code>
     * @return bool
     */
    public function getInactive()
    {
        return $this->inactive;
    }

    /**
     * Generated from protobuf field <code>bool inactive = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setInactive($var)
    {
        GPBUtil::checkBool($var);
        $this->inactive = $var;

        return $this;
    }

}

