<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *RequestUpdate Key->ID keys:
 *- ```id```: *{nervatype_1}~{refnumber_1}~~{nervatype_2}~{refnumber_2}*
 *- ```nervatype_1```: All groupvalue from Groups, where groupname equal nervatype
 *- ```ref_id_1```: *{nervatype_1}/{refnumber_1}*
 *- ```nervatype_2```: All groupvalue from Groups, where groupname equal nervatype
 *
 * Generated from protobuf message <code>nervatura.Link</code>
 */
class Link extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Reference to [Groups](#groups).id (only where groupname = 'nervatype')
     *
     * Generated from protobuf field <code>int64 nervatype_1 = 2;</code>
     */
    protected $nervatype_1 = 0;
    /**
     * Reference to {nervatype}.id
     *
     * Generated from protobuf field <code>int64 ref_id_1 = 3;</code>
     */
    protected $ref_id_1 = 0;
    /**
     * Reference to [Groups](#groups).id (only where groupname = 'nervatype')
     *
     * Generated from protobuf field <code>int64 nervatype_2 = 4;</code>
     */
    protected $nervatype_2 = 0;
    /**
     * Reference to {nervatype}.id
     *
     * Generated from protobuf field <code>int64 ref_id_2 = 5;</code>
     */
    protected $ref_id_2 = 0;
    /**
     * Link meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 16;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $nervatype_1
     *           Reference to [Groups](#groups).id (only where groupname = 'nervatype')
     *     @type int|string $ref_id_1
     *           Reference to {nervatype}.id
     *     @type int|string $nervatype_2
     *           Reference to [Groups](#groups).id (only where groupname = 'nervatype')
     *     @type int|string $ref_id_2
     *           Reference to {nervatype}.id
     *     @type \Nervatura\MetaData[]|\Google\Protobuf\Internal\RepeatedField $metadata
     *           Link meta data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'nervatype')
     *
     * Generated from protobuf field <code>int64 nervatype_1 = 2;</code>
     * @return int|string
     */
    public function getNervatype1()
    {
        return $this->nervatype_1;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'nervatype')
     *
     * Generated from protobuf field <code>int64 nervatype_1 = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNervatype1($var)
    {
        GPBUtil::checkInt64($var);
        $this->nervatype_1 = $var;

        return $this;
    }

    /**
     * Reference to {nervatype}.id
     *
     * Generated from protobuf field <code>int64 ref_id_1 = 3;</code>
     * @return int|string
     */
    public function getRefId1()
    {
        return $this->ref_id_1;
    }

    /**
     * Reference to {nervatype}.id
     *
     * Generated from protobuf field <code>int64 ref_id_1 = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRefId1($var)
    {
        GPBUtil::checkInt64($var);
        $this->ref_id_1 = $var;

        return $this;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'nervatype')
     *
     * Generated from protobuf field <code>int64 nervatype_2 = 4;</code>
     * @return int|string
     */
    public function getNervatype2()
    {
        return $this->nervatype_2;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'nervatype')
     *
     * Generated from protobuf field <code>int64 nervatype_2 = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNervatype2($var)
    {
        GPBUtil::checkInt64($var);
        $this->nervatype_2 = $var;

        return $this;
    }

    /**
     * Reference to {nervatype}.id
     *
     * Generated from protobuf field <code>int64 ref_id_2 = 5;</code>
     * @return int|string
     */
    public function getRefId2()
    {
        return $this->ref_id_2;
    }

    /**
     * Reference to {nervatype}.id
     *
     * Generated from protobuf field <code>int64 ref_id_2 = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRefId2($var)
    {
        GPBUtil::checkInt64($var);
        $this->ref_id_2 = $var;

        return $this;
    }

    /**
     * Link meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 16;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Link meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 16;</code>
     * @param \Nervatura\MetaData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\MetaData::class);
        $this->metadata = $arr;

        return $this;
    }

}

