<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *RequestUpdate Key->ID keys:
 *- ```id```: Numberdef *numberkey*
 *
 * Generated from protobuf message <code>nervatura.Numberdef</code>
 */
class Numberdef extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Unique key
     *
     * Generated from protobuf field <code>string numberkey = 2;</code>
     */
    protected $numberkey = '';
    /**
     * The text prefix of the identifier. It can be any length, but usage of special characters, spaces in the text is not recommended.
     *
     * Generated from protobuf field <code>string prefix = 3;</code>
     */
    protected $prefix = '';
    /**
     * The current status of the counter, the next sequence number will be one value higher than this one. It is possible to re-set the counter, but the uniqueness must be ensured in all cases!
     *
     * Generated from protobuf field <code>int64 curvalue = 4;</code>
     */
    protected $curvalue = 0;
    /**
     * If selected, the created identifier will contain the year.
     *
     * Generated from protobuf field <code>bool isyear = 5;</code>
     */
    protected $isyear = false;
    /**
     * The separator character in the identifier. Default: "/"
     *
     * Generated from protobuf field <code>string sep = 6;</code>
     */
    protected $sep = '';
    /**
     * The value field is arranged in such length to the right and filled with zeros.
     *
     * Generated from protobuf field <code>int64 len = 7;</code>
     */
    protected $len = 0;
    /**
     * Generated from protobuf field <code>string description = 8;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>bool visible = 9;</code>
     */
    protected $visible = false;
    /**
     * Generated from protobuf field <code>bool readonly = 10;</code>
     */
    protected $readonly = false;
    /**
     * Generated from protobuf field <code>int64 orderby = 11;</code>
     */
    protected $orderby = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $numberkey
     *           Unique key
     *     @type string $prefix
     *           The text prefix of the identifier. It can be any length, but usage of special characters, spaces in the text is not recommended.
     *     @type int|string $curvalue
     *           The current status of the counter, the next sequence number will be one value higher than this one. It is possible to re-set the counter, but the uniqueness must be ensured in all cases!
     *     @type bool $isyear
     *           If selected, the created identifier will contain the year.
     *     @type string $sep
     *           The separator character in the identifier. Default: "/"
     *     @type int|string $len
     *           The value field is arranged in such length to the right and filled with zeros.
     *     @type string $description
     *     @type bool $visible
     *     @type bool $readonly
     *     @type int|string $orderby
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Unique key
     *
     * Generated from protobuf field <code>string numberkey = 2;</code>
     * @return string
     */
    public function getNumberkey()
    {
        return $this->numberkey;
    }

    /**
     * Unique key
     *
     * Generated from protobuf field <code>string numberkey = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNumberkey($var)
    {
        GPBUtil::checkString($var, True);
        $this->numberkey = $var;

        return $this;
    }

    /**
     * The text prefix of the identifier. It can be any length, but usage of special characters, spaces in the text is not recommended.
     *
     * Generated from protobuf field <code>string prefix = 3;</code>
     * @return string
     */
    public function getPrefix()
    {
        return $this->prefix;
    }

    /**
     * The text prefix of the identifier. It can be any length, but usage of special characters, spaces in the text is not recommended.
     *
     * Generated from protobuf field <code>string prefix = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPrefix($var)
    {
        GPBUtil::checkString($var, True);
        $this->prefix = $var;

        return $this;
    }

    /**
     * The current status of the counter, the next sequence number will be one value higher than this one. It is possible to re-set the counter, but the uniqueness must be ensured in all cases!
     *
     * Generated from protobuf field <code>int64 curvalue = 4;</code>
     * @return int|string
     */
    public function getCurvalue()
    {
        return $this->curvalue;
    }

    /**
     * The current status of the counter, the next sequence number will be one value higher than this one. It is possible to re-set the counter, but the uniqueness must be ensured in all cases!
     *
     * Generated from protobuf field <code>int64 curvalue = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCurvalue($var)
    {
        GPBUtil::checkInt64($var);
        $this->curvalue = $var;

        return $this;
    }

    /**
     * If selected, the created identifier will contain the year.
     *
     * Generated from protobuf field <code>bool isyear = 5;</code>
     * @return bool
     */
    public function getIsyear()
    {
        return $this->isyear;
    }

    /**
     * If selected, the created identifier will contain the year.
     *
     * Generated from protobuf field <code>bool isyear = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsyear($var)
    {
        GPBUtil::checkBool($var);
        $this->isyear = $var;

        return $this;
    }

    /**
     * The separator character in the identifier. Default: "/"
     *
     * Generated from protobuf field <code>string sep = 6;</code>
     * @return string
     */
    public function getSep()
    {
        return $this->sep;
    }

    /**
     * The separator character in the identifier. Default: "/"
     *
     * Generated from protobuf field <code>string sep = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSep($var)
    {
        GPBUtil::checkString($var, True);
        $this->sep = $var;

        return $this;
    }

    /**
     * The value field is arranged in such length to the right and filled with zeros.
     *
     * Generated from protobuf field <code>int64 len = 7;</code>
     * @return int|string
     */
    public function getLen()
    {
        return $this->len;
    }

    /**
     * The value field is arranged in such length to the right and filled with zeros.
     *
     * Generated from protobuf field <code>int64 len = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLen($var)
    {
        GPBUtil::checkInt64($var);
        $this->len = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 8;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool visible = 9;</code>
     * @return bool
     */
    public function getVisible()
    {
        return $this->visible;
    }

    /**
     * Generated from protobuf field <code>bool visible = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setVisible($var)
    {
        GPBUtil::checkBool($var);
        $this->visible = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool readonly = 10;</code>
     * @return bool
     */
    public function getReadonly()
    {
        return $this->readonly;
    }

    /**
     * Generated from protobuf field <code>bool readonly = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setReadonly($var)
    {
        GPBUtil::checkBool($var);
        $this->readonly = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 orderby = 11;</code>
     * @return int|string
     */
    public function getOrderby()
    {
        return $this->orderby;
    }

    /**
     * Generated from protobuf field <code>int64 orderby = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderby($var)
    {
        GPBUtil::checkInt64($var);
        $this->orderby = $var;

        return $this;
    }

}

