<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *RequestUpdate Key->ID keys:
 *- ```id```: Trans and Item *transnumber~rownumber*
 *- ```trans_id```: Trans *transnumber*
 *
 * Generated from protobuf message <code>nervatura.Payment</code>
 */
class Payment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Reference to [Trans](#trans).id
     *
     * Generated from protobuf field <code>int64 trans_id = 2;</code>
     */
    protected $trans_id = 0;
    /**
     * Generated from protobuf field <code>string paiddate = 3;</code>
     */
    protected $paiddate = '';
    /**
     * Generated from protobuf field <code>double amount = 4;</code>
     */
    protected $amount = 0.0;
    /**
     * Generated from protobuf field <code>string notes = 5;</code>
     */
    protected $notes = '';
    /**
     * Payment meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 6;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $trans_id
     *           Reference to [Trans](#trans).id
     *     @type string $paiddate
     *     @type float $amount
     *     @type string $notes
     *     @type \Nervatura\MetaData[]|\Google\Protobuf\Internal\RepeatedField $metadata
     *           Payment meta data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Reference to [Trans](#trans).id
     *
     * Generated from protobuf field <code>int64 trans_id = 2;</code>
     * @return int|string
     */
    public function getTransId()
    {
        return $this->trans_id;
    }

    /**
     * Reference to [Trans](#trans).id
     *
     * Generated from protobuf field <code>int64 trans_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTransId($var)
    {
        GPBUtil::checkInt64($var);
        $this->trans_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string paiddate = 3;</code>
     * @return string
     */
    public function getPaiddate()
    {
        return $this->paiddate;
    }

    /**
     * Generated from protobuf field <code>string paiddate = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPaiddate($var)
    {
        GPBUtil::checkString($var, True);
        $this->paiddate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 4;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string notes = 5;</code>
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Generated from protobuf field <code>string notes = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->notes = $var;

        return $this;
    }

    /**
     * Payment meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Payment meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 6;</code>
     * @param \Nervatura\MetaData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\MetaData::class);
        $this->metadata = $arr;

        return $this;
    }

}

