<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *RequestUpdate Key->ID keys:
 *- ```id```: Product *partnumber*
 *- ```protype```: Valid values: *item, service*
 *- ```tax_id```: Tax *taxcode*
 *
 * Generated from protobuf message <code>nervatura.Product</code>
 */
class Product extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Unique ID. If you set it to numberdef, it will be generated at the first data save. The format and value of the next data in row is taken from the numberdef (numberkey = partnumber) data series.
     *
     * Generated from protobuf field <code>string partnumber = 2;</code>
     */
    protected $partnumber = '';
    /**
     * Reference to [Groups](#groups).id (only where groupname = 'protype')
     *
     * Generated from protobuf field <code>int64 protype = 3;</code>
     */
    protected $protype = 0;
    /**
     * The full name of the product or short description.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string unit = 5;</code>
     */
    protected $unit = '';
    /**
     * Reference to [Tax](#tax).id
     *
     * Generated from protobuf field <code>int64 tax_id = 6;</code>
     */
    protected $tax_id = 0;
    /**
     * Generated from protobuf field <code>string notes = 7;</code>
     */
    protected $notes = '';
    /**
     * Generated from protobuf field <code>bool webitem = 8;</code>
     */
    protected $webitem = false;
    /**
     * Generated from protobuf field <code>bool inactive = 9;</code>
     */
    protected $inactive = false;
    /**
     * Product meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 10;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $partnumber
     *           Unique ID. If you set it to numberdef, it will be generated at the first data save. The format and value of the next data in row is taken from the numberdef (numberkey = partnumber) data series.
     *     @type int|string $protype
     *           Reference to [Groups](#groups).id (only where groupname = 'protype')
     *     @type string $description
     *           The full name of the product or short description.
     *     @type string $unit
     *     @type int|string $tax_id
     *           Reference to [Tax](#tax).id
     *     @type string $notes
     *     @type bool $webitem
     *     @type bool $inactive
     *     @type \Nervatura\MetaData[]|\Google\Protobuf\Internal\RepeatedField $metadata
     *           Product meta data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Unique ID. If you set it to numberdef, it will be generated at the first data save. The format and value of the next data in row is taken from the numberdef (numberkey = partnumber) data series.
     *
     * Generated from protobuf field <code>string partnumber = 2;</code>
     * @return string
     */
    public function getPartnumber()
    {
        return $this->partnumber;
    }

    /**
     * Unique ID. If you set it to numberdef, it will be generated at the first data save. The format and value of the next data in row is taken from the numberdef (numberkey = partnumber) data series.
     *
     * Generated from protobuf field <code>string partnumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPartnumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->partnumber = $var;

        return $this;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'protype')
     *
     * Generated from protobuf field <code>int64 protype = 3;</code>
     * @return int|string
     */
    public function getProtype()
    {
        return $this->protype;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'protype')
     *
     * Generated from protobuf field <code>int64 protype = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProtype($var)
    {
        GPBUtil::checkInt64($var);
        $this->protype = $var;

        return $this;
    }

    /**
     * The full name of the product or short description.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * The full name of the product or short description.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unit = 5;</code>
     * @return string
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * Generated from protobuf field <code>string unit = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit = $var;

        return $this;
    }

    /**
     * Reference to [Tax](#tax).id
     *
     * Generated from protobuf field <code>int64 tax_id = 6;</code>
     * @return int|string
     */
    public function getTaxId()
    {
        return $this->tax_id;
    }

    /**
     * Reference to [Tax](#tax).id
     *
     * Generated from protobuf field <code>int64 tax_id = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaxId($var)
    {
        GPBUtil::checkInt64($var);
        $this->tax_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string notes = 7;</code>
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Generated from protobuf field <code>string notes = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->notes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool webitem = 8;</code>
     * @return bool
     */
    public function getWebitem()
    {
        return $this->webitem;
    }

    /**
     * Generated from protobuf field <code>bool webitem = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setWebitem($var)
    {
        GPBUtil::checkBool($var);
        $this->webitem = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool inactive = 9;</code>
     * @return bool
     */
    public function getInactive()
    {
        return $this->inactive;
    }

    /**
     * Generated from protobuf field <code>bool inactive = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setInactive($var)
    {
        GPBUtil::checkBool($var);
        $this->inactive = $var;

        return $this;
    }

    /**
     * Product meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Product meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 10;</code>
     * @param \Nervatura\MetaData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\MetaData::class);
        $this->metadata = $arr;

        return $this;
    }

}

