<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *RequestUpdate Key->ID keys:
 *- ```id```: Project *pronumber*
 *- ```customer_id```: Tax *custnumber*
 *
 * Generated from protobuf message <code>nervatura.Project</code>
 */
class Project extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Unique ID. If you set it to numberdef, it will be generated at the first data save. The format and value of the next data in row is taken from the numberdef (numberkey = pronumber) data series.
     *
     * Generated from protobuf field <code>string pronumber = 2;</code>
     */
    protected $pronumber = '';
    /**
     * The name of the project.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Reference to [Customer](#customer).id
     *
     * Generated from protobuf field <code>int64 customer_id = 4;</code>
     */
    protected $customer_id = null;
    /**
     * Generated from protobuf field <code>string startdate = 5;</code>
     */
    protected $startdate = null;
    /**
     * Generated from protobuf field <code>string enddate = 6;</code>
     */
    protected $enddate = null;
    /**
     * Generated from protobuf field <code>string notes = 7;</code>
     */
    protected $notes = '';
    /**
     * Generated from protobuf field <code>bool inactive = 8;</code>
     */
    protected $inactive = false;
    /**
     * Project meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 10;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $pronumber
     *           Unique ID. If you set it to numberdef, it will be generated at the first data save. The format and value of the next data in row is taken from the numberdef (numberkey = pronumber) data series.
     *     @type string $description
     *           The name of the project.
     *     @type int|string $customer_id
     *           Reference to [Customer](#customer).id
     *     @type string $startdate
     *     @type string $enddate
     *     @type string $notes
     *     @type bool $inactive
     *     @type \Nervatura\MetaData[]|\Google\Protobuf\Internal\RepeatedField $metadata
     *           Project meta data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Unique ID. If you set it to numberdef, it will be generated at the first data save. The format and value of the next data in row is taken from the numberdef (numberkey = pronumber) data series.
     *
     * Generated from protobuf field <code>string pronumber = 2;</code>
     * @return string
     */
    public function getPronumber()
    {
        return $this->pronumber;
    }

    /**
     * Unique ID. If you set it to numberdef, it will be generated at the first data save. The format and value of the next data in row is taken from the numberdef (numberkey = pronumber) data series.
     *
     * Generated from protobuf field <code>string pronumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPronumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->pronumber = $var;

        return $this;
    }

    /**
     * The name of the project.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * The name of the project.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Reference to [Customer](#customer).id
     *
     * Generated from protobuf field <code>int64 customer_id = 4;</code>
     * @return int|string
     */
    public function getCustomerId()
    {
        return isset($this->customer_id) ? $this->customer_id : 0;
    }

    public function hasCustomerId()
    {
        return isset($this->customer_id);
    }

    public function clearCustomerId()
    {
        unset($this->customer_id);
    }

    /**
     * Reference to [Customer](#customer).id
     *
     * Generated from protobuf field <code>int64 customer_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCustomerId($var)
    {
        GPBUtil::checkInt64($var);
        $this->customer_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string startdate = 5;</code>
     * @return string
     */
    public function getStartdate()
    {
        return isset($this->startdate) ? $this->startdate : '';
    }

    public function hasStartdate()
    {
        return isset($this->startdate);
    }

    public function clearStartdate()
    {
        unset($this->startdate);
    }

    /**
     * Generated from protobuf field <code>string startdate = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStartdate($var)
    {
        GPBUtil::checkString($var, True);
        $this->startdate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string enddate = 6;</code>
     * @return string
     */
    public function getEnddate()
    {
        return isset($this->enddate) ? $this->enddate : '';
    }

    public function hasEnddate()
    {
        return isset($this->enddate);
    }

    public function clearEnddate()
    {
        unset($this->enddate);
    }

    /**
     * Generated from protobuf field <code>string enddate = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setEnddate($var)
    {
        GPBUtil::checkString($var, True);
        $this->enddate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string notes = 7;</code>
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Generated from protobuf field <code>string notes = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->notes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool inactive = 8;</code>
     * @return bool
     */
    public function getInactive()
    {
        return $this->inactive;
    }

    /**
     * Generated from protobuf field <code>bool inactive = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setInactive($var)
    {
        GPBUtil::checkBool($var);
        $this->inactive = $var;

        return $this;
    }

    /**
     * Project meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Project meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 10;</code>
     * @param \Nervatura\MetaData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\MetaData::class);
        $this->metadata = $arr;

        return $this;
    }

}

