<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *RequestUpdate Key->ID keys:
 *- ```id```: Rate *ratetype~ratedate~curr~planumber*
 *- ```place_id```: Place *planumber*
 *- ```ratetype```: Valid values: *rate, buy, sell,average*
 *- ```rategroup```: all groupvalue from Groups, where groupname equal rategroup
 *
 * Generated from protobuf message <code>nervatura.Rate</code>
 */
class Rate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Reference to [Groups](#groups).id (only where groupname = 'ratetype')
     *
     * Generated from protobuf field <code>int64 ratetype = 2;</code>
     */
    protected $ratetype = 0;
    /**
     * Generated from protobuf field <code>string ratedate = 3;</code>
     */
    protected $ratedate = '';
    /**
     * Generated from protobuf field <code>string curr = 4;</code>
     */
    protected $curr = '';
    /**
     * Reference to [Place](#place).id
     *
     * Generated from protobuf field <code>int64 place_id = 5;</code>
     */
    protected $place_id = null;
    /**
     * Reference to [Groups](#groups).id (only where groupname = 'rategroup')
     *
     * Generated from protobuf field <code>int64 rategroup = 6;</code>
     */
    protected $rategroup = null;
    /**
     * Rate or interest value
     *
     * Generated from protobuf field <code>double ratevalue = 7;</code>
     */
    protected $ratevalue = 0.0;
    /**
     * Rate meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 10;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $ratetype
     *           Reference to [Groups](#groups).id (only where groupname = 'ratetype')
     *     @type string $ratedate
     *     @type string $curr
     *     @type int|string $place_id
     *           Reference to [Place](#place).id
     *     @type int|string $rategroup
     *           Reference to [Groups](#groups).id (only where groupname = 'rategroup')
     *     @type float $ratevalue
     *           Rate or interest value
     *     @type \Nervatura\MetaData[]|\Google\Protobuf\Internal\RepeatedField $metadata
     *           Rate meta data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'ratetype')
     *
     * Generated from protobuf field <code>int64 ratetype = 2;</code>
     * @return int|string
     */
    public function getRatetype()
    {
        return $this->ratetype;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'ratetype')
     *
     * Generated from protobuf field <code>int64 ratetype = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRatetype($var)
    {
        GPBUtil::checkInt64($var);
        $this->ratetype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ratedate = 3;</code>
     * @return string
     */
    public function getRatedate()
    {
        return $this->ratedate;
    }

    /**
     * Generated from protobuf field <code>string ratedate = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRatedate($var)
    {
        GPBUtil::checkString($var, True);
        $this->ratedate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string curr = 4;</code>
     * @return string
     */
    public function getCurr()
    {
        return $this->curr;
    }

    /**
     * Generated from protobuf field <code>string curr = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCurr($var)
    {
        GPBUtil::checkString($var, True);
        $this->curr = $var;

        return $this;
    }

    /**
     * Reference to [Place](#place).id
     *
     * Generated from protobuf field <code>int64 place_id = 5;</code>
     * @return int|string
     */
    public function getPlaceId()
    {
        return isset($this->place_id) ? $this->place_id : 0;
    }

    public function hasPlaceId()
    {
        return isset($this->place_id);
    }

    public function clearPlaceId()
    {
        unset($this->place_id);
    }

    /**
     * Reference to [Place](#place).id
     *
     * Generated from protobuf field <code>int64 place_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPlaceId($var)
    {
        GPBUtil::checkInt64($var);
        $this->place_id = $var;

        return $this;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'rategroup')
     *
     * Generated from protobuf field <code>int64 rategroup = 6;</code>
     * @return int|string
     */
    public function getRategroup()
    {
        return isset($this->rategroup) ? $this->rategroup : 0;
    }

    public function hasRategroup()
    {
        return isset($this->rategroup);
    }

    public function clearRategroup()
    {
        unset($this->rategroup);
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'rategroup')
     *
     * Generated from protobuf field <code>int64 rategroup = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRategroup($var)
    {
        GPBUtil::checkInt64($var);
        $this->rategroup = $var;

        return $this;
    }

    /**
     * Rate or interest value
     *
     * Generated from protobuf field <code>double ratevalue = 7;</code>
     * @return float
     */
    public function getRatevalue()
    {
        return $this->ratevalue;
    }

    /**
     * Rate or interest value
     *
     * Generated from protobuf field <code>double ratevalue = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setRatevalue($var)
    {
        GPBUtil::checkDouble($var);
        $this->ratevalue = $var;

        return $this;
    }

    /**
     * Rate meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Rate meta data
     *
     * Generated from protobuf field <code>repeated .nervatura.MetaData metadata = 10;</code>
     * @param \Nervatura\MetaData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\MetaData::class);
        $this->metadata = $arr;

        return $this;
    }

}

