<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.ReportOrientation</code>
 */
class ReportOrientation
{
    /**
     * Generated from protobuf enum <code>portrait = 0;</code>
     */
    const portrait = 0;
    /**
     * Generated from protobuf enum <code>landscape = 1;</code>
     */
    const landscape = 1;

    private static $valueToName = [
        self::portrait => 'portrait',
        self::landscape => 'landscape',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtolower($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

