<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.RequestGet</code>
 */
class RequestGet extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.nervatura.DataType nervatype = 1;</code>
     */
    protected $nervatype = 0;
    /**
     * Generated from protobuf field <code>bool metadata = 2;</code>
     */
    protected $metadata = false;
    /**
     * Generated from protobuf field <code>repeated int64 ids = 3;</code>
     */
    private $ids;
    /**
     * Generated from protobuf field <code>repeated string filter = 7;</code>
     */
    private $filter;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $nervatype
     *     @type bool $metadata
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $ids
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $filter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.nervatura.DataType nervatype = 1;</code>
     * @return int
     */
    public function getNervatype()
    {
        return $this->nervatype;
    }

    /**
     * Generated from protobuf field <code>.nervatura.DataType nervatype = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNervatype($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\DataType::class);
        $this->nervatype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool metadata = 2;</code>
     * @return bool
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>bool metadata = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkBool($var);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 ids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIds()
    {
        return $this->ids;
    }

    /**
     * Generated from protobuf field <code>repeated int64 ids = 3;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string filter = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * Generated from protobuf field <code>repeated string filter = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFilter($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->filter = $arr;

        return $this;
    }

}

