<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.RequestUserPassword</code>
 */
class RequestUserPassword extends \Google\Protobuf\Internal\Message
{
    /**
     * New password
     *
     * Generated from protobuf field <code>string password = 1;</code>
     */
    protected $password = '';
    /**
     * New password confirmation
     *
     * Generated from protobuf field <code>string confirm = 2;</code>
     */
    protected $confirm = '';
    /**
     * Optional. Only if different from the logged in user. Admin user group membership required.
     *
     * Generated from protobuf field <code>string username = 3;</code>
     */
    protected $username = '';
    /**
     * Optional. Only if different from the logged in user. Admin user group membership required.
     *
     * Generated from protobuf field <code>string custnumber = 4;</code>
     */
    protected $custnumber = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $password
     *           New password
     *     @type string $confirm
     *           New password confirmation
     *     @type string $username
     *           Optional. Only if different from the logged in user. Admin user group membership required.
     *     @type string $custnumber
     *           Optional. Only if different from the logged in user. Admin user group membership required.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * New password
     *
     * Generated from protobuf field <code>string password = 1;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * New password
     *
     * Generated from protobuf field <code>string password = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * New password confirmation
     *
     * Generated from protobuf field <code>string confirm = 2;</code>
     * @return string
     */
    public function getConfirm()
    {
        return $this->confirm;
    }

    /**
     * New password confirmation
     *
     * Generated from protobuf field <code>string confirm = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setConfirm($var)
    {
        GPBUtil::checkString($var, True);
        $this->confirm = $var;

        return $this;
    }

    /**
     * Optional. Only if different from the logged in user. Admin user group membership required.
     *
     * Generated from protobuf field <code>string username = 3;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Optional. Only if different from the logged in user. Admin user group membership required.
     *
     * Generated from protobuf field <code>string username = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Optional. Only if different from the logged in user. Admin user group membership required.
     *
     * Generated from protobuf field <code>string custnumber = 4;</code>
     * @return string
     */
    public function getCustnumber()
    {
        return $this->custnumber;
    }

    /**
     * Optional. Only if different from the logged in user. Admin user group membership required.
     *
     * Generated from protobuf field <code>string custnumber = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCustnumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->custnumber = $var;

        return $this;
    }

}

