<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.RequestReport</code>
 */
class RequestReport extends \Google\Protobuf\Internal\Message
{
    /**
     * Example : ntr_invoice_en
     *
     * Generated from protobuf field <code>string reportkey = 1;</code>
     */
    protected $reportkey = '';
    /**
     * Generated from protobuf field <code>.nervatura.ReportOrientation orientation = 2;</code>
     */
    protected $orientation = 0;
    /**
     * Generated from protobuf field <code>.nervatura.ReportSize size = 3;</code>
     */
    protected $size = 0;
    /**
     * Generated from protobuf field <code>.nervatura.ReportOutput output = 4;</code>
     */
    protected $output = 0;
    /**
     * Generated from protobuf field <code>.nervatura.ReportType type = 5;</code>
     */
    protected $type = 0;
    /**
     * Example : DMINV/00001
     *
     * Generated from protobuf field <code>string refnumber = 6;</code>
     */
    protected $refnumber = '';
    /**
     * Custom report JSON template
     *
     * Generated from protobuf field <code>string template = 7;</code>
     */
    protected $template = '';
    /**
     * Generated from protobuf field <code>map<string, .nervatura.Value> filters = 8;</code>
     */
    private $filters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $reportkey
     *           Example : ntr_invoice_en
     *     @type int $orientation
     *     @type int $size
     *     @type int $output
     *     @type int $type
     *     @type string $refnumber
     *           Example : DMINV/00001
     *     @type string $template
     *           Custom report JSON template
     *     @type array|\Google\Protobuf\Internal\MapField $filters
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Example : ntr_invoice_en
     *
     * Generated from protobuf field <code>string reportkey = 1;</code>
     * @return string
     */
    public function getReportkey()
    {
        return $this->reportkey;
    }

    /**
     * Example : ntr_invoice_en
     *
     * Generated from protobuf field <code>string reportkey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setReportkey($var)
    {
        GPBUtil::checkString($var, True);
        $this->reportkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ReportOrientation orientation = 2;</code>
     * @return int
     */
    public function getOrientation()
    {
        return $this->orientation;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ReportOrientation orientation = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOrientation($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\ReportOrientation::class);
        $this->orientation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ReportSize size = 3;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ReportSize size = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\ReportSize::class);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ReportOutput output = 4;</code>
     * @return int
     */
    public function getOutput()
    {
        return $this->output;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ReportOutput output = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOutput($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\ReportOutput::class);
        $this->output = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ReportType type = 5;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ReportType type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\ReportType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Example : DMINV/00001
     *
     * Generated from protobuf field <code>string refnumber = 6;</code>
     * @return string
     */
    public function getRefnumber()
    {
        return $this->refnumber;
    }

    /**
     * Example : DMINV/00001
     *
     * Generated from protobuf field <code>string refnumber = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRefnumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->refnumber = $var;

        return $this;
    }

    /**
     * Custom report JSON template
     *
     * Generated from protobuf field <code>string template = 7;</code>
     * @return string
     */
    public function getTemplate()
    {
        return $this->template;
    }

    /**
     * Custom report JSON template
     *
     * Generated from protobuf field <code>string template = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTemplate($var)
    {
        GPBUtil::checkString($var, True);
        $this->template = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .nervatura.Value> filters = 8;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getFilters()
    {
        return $this->filters;
    }

    /**
     * Generated from protobuf field <code>map<string, .nervatura.Value> filters = 8;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setFilters($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\Value::class);
        $this->filters = $arr;

        return $this;
    }

}

