<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.RequestReportDelete</code>
 */
class RequestReportDelete extends \Google\Protobuf\Internal\Message
{
    /**
     * Example : ntr_invoice_en
     *
     * Generated from protobuf field <code>string reportkey = 1;</code>
     */
    protected $reportkey = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $reportkey
     *           Example : ntr_invoice_en
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Example : ntr_invoice_en
     *
     * Generated from protobuf field <code>string reportkey = 1;</code>
     * @return string
     */
    public function getReportkey()
    {
        return $this->reportkey;
    }

    /**
     * Example : ntr_invoice_en
     *
     * Generated from protobuf field <code>string reportkey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setReportkey($var)
    {
        GPBUtil::checkString($var, True);
        $this->reportkey = $var;

        return $this;
    }

}

