<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.RequestUpdate</code>
 */
class RequestUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.nervatura.DataType nervatype = 1;</code>
     */
    protected $nervatype = 0;
    /**
     * Generated from protobuf field <code>repeated .nervatura.RequestUpdate.Item items = 2;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $nervatype
     *     @type \Nervatura\RequestUpdate\Item[]|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.nervatura.DataType nervatype = 1;</code>
     * @return int
     */
    public function getNervatype()
    {
        return $this->nervatype;
    }

    /**
     * Generated from protobuf field <code>.nervatura.DataType nervatype = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNervatype($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\DataType::class);
        $this->nervatype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.RequestUpdate.Item items = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.RequestUpdate.Item items = 2;</code>
     * @param \Nervatura\RequestUpdate\Item[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\RequestUpdate\Item::class);
        $this->items = $arr;

        return $this;
    }

}

