<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Delete parameters
 *
 * Generated from protobuf message <code>nervatura.RequestDelete</code>
 */
class RequestDelete extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.nervatura.DataType nervatype = 1;</code>
     */
    protected $nervatype = 0;
    /**
     * The object ID
     *
     * Generated from protobuf field <code>int64 id = 36;</code>
     */
    protected $id = 0;
    /**
     * Use Key instead of ID
     *
     * Generated from protobuf field <code>string key = 37;</code>
     */
    protected $key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $nervatype
     *     @type int|string $id
     *           The object ID
     *     @type string $key
     *           Use Key instead of ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.nervatura.DataType nervatype = 1;</code>
     * @return int
     */
    public function getNervatype()
    {
        return $this->nervatype;
    }

    /**
     * Generated from protobuf field <code>.nervatura.DataType nervatype = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNervatype($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\DataType::class);
        $this->nervatype = $var;

        return $this;
    }

    /**
     * The object ID
     *
     * Generated from protobuf field <code>int64 id = 36;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * The object ID
     *
     * Generated from protobuf field <code>int64 id = 36;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Use Key instead of ID
     *
     * Generated from protobuf field <code>string key = 37;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Use Key instead of ID
     *
     * Generated from protobuf field <code>string key = 37;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

}

