<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Result log data
 *
 * Generated from protobuf message <code>nervatura.ResponseDatabaseCreate</code>
 */
class ResponseDatabaseCreate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.nervatura.ResponseRows details = 1;</code>
     */
    protected $details = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nervatura\ResponseRows $details
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.nervatura.ResponseRows details = 1;</code>
     * @return \Nervatura\ResponseRows
     */
    public function getDetails()
    {
        return isset($this->details) ? $this->details : null;
    }

    public function hasDetails()
    {
        return isset($this->details);
    }

    public function clearDetails()
    {
        unset($this->details);
    }

    /**
     * Generated from protobuf field <code>.nervatura.ResponseRows details = 1;</code>
     * @param \Nervatura\ResponseRows $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\ResponseRows::class);
        $this->details = $var;

        return $this;
    }

}

