<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.ResponseView</code>
 */
class ResponseView extends \Google\Protobuf\Internal\Message
{
    /**
     * key - results map
     *
     * Generated from protobuf field <code>map<string, .nervatura.ResponseRows> values = 1;</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $values
     *           key - results map
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * key - results map
     *
     * Generated from protobuf field <code>map<string, .nervatura.ResponseRows> values = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * key - results map
     *
     * Generated from protobuf field <code>map<string, .nervatura.ResponseRows> values = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\ResponseRows::class);
        $this->values = $arr;

        return $this;
    }

}

