<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.ResponseUserLogin</code>
 */
class ResponseUserLogin extends \Google\Protobuf\Internal\Message
{
    /**
     * Access JWT token
     *
     * Generated from protobuf field <code>string token = 1;</code>
     */
    protected $token = '';
    /**
     * Type of database
     *
     * Generated from protobuf field <code>string engine = 2;</code>
     */
    protected $engine = '';
    /**
     * Service version
     *
     * Generated from protobuf field <code>string version = 3;</code>
     */
    protected $version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token
     *           Access JWT token
     *     @type string $engine
     *           Type of database
     *     @type string $version
     *           Service version
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Access JWT token
     *
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Access JWT token
     *
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Type of database
     *
     * Generated from protobuf field <code>string engine = 2;</code>
     * @return string
     */
    public function getEngine()
    {
        return $this->engine;
    }

    /**
     * Type of database
     *
     * Generated from protobuf field <code>string engine = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEngine($var)
    {
        GPBUtil::checkString($var, True);
        $this->engine = $var;

        return $this;
    }

    /**
     * Service version
     *
     * Generated from protobuf field <code>string version = 3;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Service version
     *
     * Generated from protobuf field <code>string version = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

}

