<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * If the ID (or Key) value is missing, it creates a new item.
 *
 * Generated from protobuf message <code>nervatura.ResponseUpdate</code>
 */
class ResponseUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Returns the all new/updated IDs values.
     *
     * Generated from protobuf field <code>repeated int64 values = 1;</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $values
     *           Returns the all new/updated IDs values.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Returns the all new/updated IDs values.
     *
     * Generated from protobuf field <code>repeated int64 values = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Returns the all new/updated IDs values.
     *
     * Generated from protobuf field <code>repeated int64 values = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->values = $arr;

        return $this;
    }

}

