<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Access token claims.
 *
 * Generated from protobuf message <code>nervatura.ResponseTokenDecode</code>
 */
class ResponseTokenDecode extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string username = 1;</code>
     */
    protected $username = '';
    /**
     * Generated from protobuf field <code>string database = 2;</code>
     */
    protected $database = '';
    /**
     * JWT expiration time
     *
     * Generated from protobuf field <code>double exp = 3;</code>
     */
    protected $exp = 0.0;
    /**
     * Generated from protobuf field <code>string iss = 4;</code>
     */
    protected $iss = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $username
     *     @type string $database
     *     @type float $exp
     *           JWT expiration time
     *     @type string $iss
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string username = 1;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string database = 2;</code>
     * @return string
     */
    public function getDatabase()
    {
        return $this->database;
    }

    /**
     * Generated from protobuf field <code>string database = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDatabase($var)
    {
        GPBUtil::checkString($var, True);
        $this->database = $var;

        return $this;
    }

    /**
     * JWT expiration time
     *
     * Generated from protobuf field <code>double exp = 3;</code>
     * @return float
     */
    public function getExp()
    {
        return $this->exp;
    }

    /**
     * JWT expiration time
     *
     * Generated from protobuf field <code>double exp = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setExp($var)
    {
        GPBUtil::checkDouble($var);
        $this->exp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string iss = 4;</code>
     * @return string
     */
    public function getIss()
    {
        return $this->iss;
    }

    /**
     * Generated from protobuf field <code>string iss = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIss($var)
    {
        GPBUtil::checkString($var, True);
        $this->iss = $var;

        return $this;
    }

}

