<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *RequestUpdate Key->ID keys:
 *- ```id```: UiMessage *{secname}~{fieldname}~{lang}*
 *
 * Generated from protobuf message <code>nervatura.UiMessage</code>
 */
class UiMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string secname = 2;</code>
     */
    protected $secname = '';
    /**
     * Generated from protobuf field <code>string fieldname = 3;</code>
     */
    protected $fieldname = '';
    /**
     * Generated from protobuf field <code>string lang = 4;</code>
     */
    protected $lang = '';
    /**
     * Generated from protobuf field <code>string msg = 5;</code>
     */
    protected $msg = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $secname
     *     @type string $fieldname
     *     @type string $lang
     *     @type string $msg
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string secname = 2;</code>
     * @return string
     */
    public function getSecname()
    {
        return $this->secname;
    }

    /**
     * Generated from protobuf field <code>string secname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSecname($var)
    {
        GPBUtil::checkString($var, True);
        $this->secname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fieldname = 3;</code>
     * @return string
     */
    public function getFieldname()
    {
        return $this->fieldname;
    }

    /**
     * Generated from protobuf field <code>string fieldname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fieldname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lang = 4;</code>
     * @return string
     */
    public function getLang()
    {
        return $this->lang;
    }

    /**
     * Generated from protobuf field <code>string lang = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLang($var)
    {
        GPBUtil::checkString($var, True);
        $this->lang = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg = 5;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

}

