<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *RequestUpdate Key->ID keys:
 *- ```id```: UiMenu *menukey*
 *
 * Generated from protobuf message <code>nervatura.UiMenu</code>
 */
class UiMenu extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string menukey = 2;</code>
     */
    protected $menukey = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string modul = 4;</code>
     */
    protected $modul = '';
    /**
     * Generated from protobuf field <code>string icon = 5;</code>
     */
    protected $icon = '';
    /**
     * Reference to [Groups](#groups).id (only where groupname = 'method')
     *
     * Generated from protobuf field <code>int64 method = 6;</code>
     */
    protected $method = 0;
    /**
     * Generated from protobuf field <code>string funcname = 7;</code>
     */
    protected $funcname = '';
    /**
     * Generated from protobuf field <code>string address = 8;</code>
     */
    protected $address = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $menukey
     *     @type string $description
     *     @type string $modul
     *     @type string $icon
     *     @type int|string $method
     *           Reference to [Groups](#groups).id (only where groupname = 'method')
     *     @type string $funcname
     *     @type string $address
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string menukey = 2;</code>
     * @return string
     */
    public function getMenukey()
    {
        return $this->menukey;
    }

    /**
     * Generated from protobuf field <code>string menukey = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMenukey($var)
    {
        GPBUtil::checkString($var, True);
        $this->menukey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string modul = 4;</code>
     * @return string
     */
    public function getModul()
    {
        return $this->modul;
    }

    /**
     * Generated from protobuf field <code>string modul = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setModul($var)
    {
        GPBUtil::checkString($var, True);
        $this->modul = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string icon = 5;</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->icon;
    }

    /**
     * Generated from protobuf field <code>string icon = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->icon = $var;

        return $this;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'method')
     *
     * Generated from protobuf field <code>int64 method = 6;</code>
     * @return int|string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'method')
     *
     * Generated from protobuf field <code>int64 method = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkInt64($var);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string funcname = 7;</code>
     * @return string
     */
    public function getFuncname()
    {
        return $this->funcname;
    }

    /**
     * Generated from protobuf field <code>string funcname = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFuncname($var)
    {
        GPBUtil::checkString($var, True);
        $this->funcname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 8;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

}

