<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *RequestUpdate Key->ID keys:
 *- ```id```: UiMenufields *{menukey}~{fieldname}*
 *- ```menu_id```: UiMenu *menukey*
 *
 * Generated from protobuf message <code>nervatura.UiMenufields</code>
 */
class UiMenufields extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Reference to [UiMenu](#UiMenu).id
     *
     * Generated from protobuf field <code>int64 menu_id = 2;</code>
     */
    protected $menu_id = 0;
    /**
     * Generated from protobuf field <code>string fieldname = 3;</code>
     */
    protected $fieldname = '';
    /**
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Reference to [Groups](#groups).id (only where groupname = 'fieldtype')
     *
     * Generated from protobuf field <code>int64 fieldtype = 5;</code>
     */
    protected $fieldtype = 0;
    /**
     * Generated from protobuf field <code>int64 orderby = 6;</code>
     */
    protected $orderby = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $menu_id
     *           Reference to [UiMenu](#UiMenu).id
     *     @type string $fieldname
     *     @type string $description
     *     @type int|string $fieldtype
     *           Reference to [Groups](#groups).id (only where groupname = 'fieldtype')
     *     @type int|string $orderby
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Reference to [UiMenu](#UiMenu).id
     *
     * Generated from protobuf field <code>int64 menu_id = 2;</code>
     * @return int|string
     */
    public function getMenuId()
    {
        return $this->menu_id;
    }

    /**
     * Reference to [UiMenu](#UiMenu).id
     *
     * Generated from protobuf field <code>int64 menu_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMenuId($var)
    {
        GPBUtil::checkInt64($var);
        $this->menu_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fieldname = 3;</code>
     * @return string
     */
    public function getFieldname()
    {
        return $this->fieldname;
    }

    /**
     * Generated from protobuf field <code>string fieldname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fieldname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'fieldtype')
     *
     * Generated from protobuf field <code>int64 fieldtype = 5;</code>
     * @return int|string
     */
    public function getFieldtype()
    {
        return $this->fieldtype;
    }

    /**
     * Reference to [Groups](#groups).id (only where groupname = 'fieldtype')
     *
     * Generated from protobuf field <code>int64 fieldtype = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFieldtype($var)
    {
        GPBUtil::checkInt64($var);
        $this->fieldtype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 orderby = 6;</code>
     * @return int|string
     */
    public function getOrderby()
    {
        return $this->orderby;
    }

    /**
     * Generated from protobuf field <code>int64 orderby = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderby($var)
    {
        GPBUtil::checkInt64($var);
        $this->orderby = $var;

        return $this;
    }

}

