<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *RequestUpdate Key->ID keys:
 *- ```id```: *{empnumber}~{section}~{cfgroup}~{cfname}*
 *- ```employee_id```: Employee *{empnumber}*
 *
 * Generated from protobuf message <code>nervatura.UiUserconfig</code>
 */
class UiUserconfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Reference to [Employee](#employee).id
     *
     * Generated from protobuf field <code>int64 employee_id = 2;</code>
     */
    protected $employee_id = null;
    /**
     * Generated from protobuf field <code>string section = 3;</code>
     */
    protected $section = null;
    /**
     * Generated from protobuf field <code>string cfgroup = 4;</code>
     */
    protected $cfgroup = '';
    /**
     * Generated from protobuf field <code>string cfname = 5;</code>
     */
    protected $cfname = '';
    /**
     * Generated from protobuf field <code>string cfvalue = 6;</code>
     */
    protected $cfvalue = null;
    /**
     * Generated from protobuf field <code>int64 orderby = 7;</code>
     */
    protected $orderby = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $employee_id
     *           Reference to [Employee](#employee).id
     *     @type string $section
     *     @type string $cfgroup
     *     @type string $cfname
     *     @type string $cfvalue
     *     @type int|string $orderby
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Reference to [Employee](#employee).id
     *
     * Generated from protobuf field <code>int64 employee_id = 2;</code>
     * @return int|string
     */
    public function getEmployeeId()
    {
        return isset($this->employee_id) ? $this->employee_id : 0;
    }

    public function hasEmployeeId()
    {
        return isset($this->employee_id);
    }

    public function clearEmployeeId()
    {
        unset($this->employee_id);
    }

    /**
     * Reference to [Employee](#employee).id
     *
     * Generated from protobuf field <code>int64 employee_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEmployeeId($var)
    {
        GPBUtil::checkInt64($var);
        $this->employee_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string section = 3;</code>
     * @return string
     */
    public function getSection()
    {
        return isset($this->section) ? $this->section : '';
    }

    public function hasSection()
    {
        return isset($this->section);
    }

    public function clearSection()
    {
        unset($this->section);
    }

    /**
     * Generated from protobuf field <code>string section = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSection($var)
    {
        GPBUtil::checkString($var, True);
        $this->section = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cfgroup = 4;</code>
     * @return string
     */
    public function getCfgroup()
    {
        return $this->cfgroup;
    }

    /**
     * Generated from protobuf field <code>string cfgroup = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCfgroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->cfgroup = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cfname = 5;</code>
     * @return string
     */
    public function getCfname()
    {
        return $this->cfname;
    }

    /**
     * Generated from protobuf field <code>string cfname = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCfname($var)
    {
        GPBUtil::checkString($var, True);
        $this->cfname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cfvalue = 6;</code>
     * @return string
     */
    public function getCfvalue()
    {
        return isset($this->cfvalue) ? $this->cfvalue : '';
    }

    public function hasCfvalue()
    {
        return isset($this->cfvalue);
    }

    public function clearCfvalue()
    {
        unset($this->cfvalue);
    }

    /**
     * Generated from protobuf field <code>string cfvalue = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCfvalue($var)
    {
        GPBUtil::checkString($var, True);
        $this->cfvalue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 orderby = 7;</code>
     * @return int|string
     */
    public function getOrderby()
    {
        return $this->orderby;
    }

    /**
     * Generated from protobuf field <code>int64 orderby = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderby($var)
    {
        GPBUtil::checkInt64($var);
        $this->orderby = $var;

        return $this;
    }

}

