<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Nervatura\ResponseReportList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.ResponseReportList.Info</code>
 */
class Info extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string reportkey = 1;</code>
     */
    protected $reportkey = '';
    /**
     * Generated from protobuf field <code>string repname = 2;</code>
     */
    protected $repname = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string label = 4;</code>
     */
    protected $label = '';
    /**
     * Generated from protobuf field <code>string reptype = 5;</code>
     */
    protected $reptype = '';
    /**
     * Generated from protobuf field <code>string filename = 6;</code>
     */
    protected $filename = '';
    /**
     * Generated from protobuf field <code>bool installed = 7;</code>
     */
    protected $installed = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $reportkey
     *     @type string $repname
     *     @type string $description
     *     @type string $label
     *     @type string $reptype
     *     @type string $filename
     *     @type bool $installed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string reportkey = 1;</code>
     * @return string
     */
    public function getReportkey()
    {
        return $this->reportkey;
    }

    /**
     * Generated from protobuf field <code>string reportkey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setReportkey($var)
    {
        GPBUtil::checkString($var, True);
        $this->reportkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string repname = 2;</code>
     * @return string
     */
    public function getRepname()
    {
        return $this->repname;
    }

    /**
     * Generated from protobuf field <code>string repname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRepname($var)
    {
        GPBUtil::checkString($var, True);
        $this->repname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string label = 4;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reptype = 5;</code>
     * @return string
     */
    public function getReptype()
    {
        return $this->reptype;
    }

    /**
     * Generated from protobuf field <code>string reptype = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setReptype($var)
    {
        GPBUtil::checkString($var, True);
        $this->reptype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string filename = 6;</code>
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Generated from protobuf field <code>string filename = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFilename($var)
    {
        GPBUtil::checkString($var, True);
        $this->filename = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool installed = 7;</code>
     * @return bool
     */
    public function getInstalled()
    {
        return $this->installed;
    }

    /**
     * Generated from protobuf field <code>bool installed = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setInstalled($var)
    {
        GPBUtil::checkBool($var);
        $this->installed = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Info::class, \Nervatura\ResponseReportList_Info::class);

